export const sampleLeagues = [
  {
    rosters: [
      {
        co_owners: null,
        keepers: null,
        league_id: "1",
        metadata: {
          record: "LWWLWWLLWWWWWWL",
          streak: "1L",
        },
        owner_id: "1",
        player_map: null,
        players: [
          {
            overallRank: 9,
            name: "Rashee Rice",
            position: "WR",
            isSelected: false,
            redraftValue: 7581,
            trend30Day: 1627,
            sleeperId: "10229",
          },
          {
            overallRank: 110,
            name: "Harold Fannin",
            position: "TE",
            isSelected: false,
            redraftValue: 627,
            trend30Day: 219,
            sleeperId: "12506",
          },
          {
            overallRank: 18,
            name: "Ashton Jeanty",
            position: "RB",
            isSelected: false,
            redraftValue: 5667,
            trend30Day: 1277,
            sleeperId: "12527",
          },
          {
            overallRank: 33,
            name: "TreVeyon Henderson",
            position: "RB",
            isSelected: false,
            redraftValue: 3801,
            trend30Day: -368,
            sleeperId: "12529",
          },
          {
            overallRank: 49,
            name: "Dak Prescott",
            position: "QB",
            isSelected: false,
            redraftValue: 2951,
            trend30Day: 943,
            sleeperId: "3294",
          },
          {
            overallRank: 3,
            name: "Christian McCaffrey",
            position: "RB",
            isSelected: false,
            redraftValue: 9464,
            trend30Day: -628,
            sleeperId: "4034",
          },
          {
            overallRank: 52,
            name: "Joe Burrow",
            position: "QB",
            isSelected: false,
            redraftValue: 2725,
            trend30Day: 658,
            sleeperId: "6770",
          },
          {
            overallRank: 44,
            name: "Rico Dowdle",
            position: "RB",
            isSelected: false,
            redraftValue: 3088,
            trend30Day: -317,
            sleeperId: "7021",
          },
          {
            overallRank: 6,
            name: "Ja'Marr Chase",
            position: "WR",
            isSelected: false,
            redraftValue: 9111,
            trend30Day: -177,
            sleeperId: "7564",
          },
          {
            overallRank: 21,
            name: "Nico Collins",
            position: "WR",
            isSelected: false,
            redraftValue: 5629,
            trend30Day: 708,
            sleeperId: "7569",
          },
          {
            overallRank: 24,
            name: "Drake London",
            position: "WR",
            isSelected: false,
            redraftValue: 5345,
            trend30Day: 660,
            sleeperId: "8112",
          },
          {
            overallRank: 23,
            name: "Chase Brown",
            position: "RB",
            isSelected: false,
            redraftValue: 5312,
            trend30Day: 1163,
            sleeperId: "9224",
          },
          {
            overallRank: 7,
            name: "De'Von Achane",
            position: "RB",
            isSelected: false,
            redraftValue: 8960,
            trend30Day: 368,
            sleeperId: "9226",
          },
          {
            overallRank: 5,
            name: "Bijan Robinson",
            position: "RB",
            isSelected: false,
            redraftValue: 9138,
            trend30Day: 562,
            sleeperId: "9509",
          },
        ],
        reserve: null,
        roster_id: 1,
        settings: {
          fpts: 2442,
          fpts_against: 2127,
          fpts_against_decimal: 48,
          fpts_decimal: 28,
          losses: 5,
          ppts: 2713,
          ppts_decimal: 36,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 1,
          wins: 10,
        },
        starters: [
          "3294",
          "4034",
          "9224",
          "7569",
          "7564",
          "12506",
          "9509",
          "9226",
          "6770",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember1",
          is_bot: false,
          is_owner: true,
          league_id: "1",
          metadata: {
            allow_pn: "on",
            archived: "off",
            mention_pn: "on",
          },
          settings: null,
          user_id: "1",
        },
        trend30Day: 6695,
        totalValue: 79399,
      },
      {
        co_owners: null,
        keepers: null,
        league_id: "1",
        metadata: {
          record: "WWLWLLLWLLWLWWW",
          streak: "3W",
        },
        owner_id: "2",
        player_map: null,
        players: [
          {
            overallRank: 20,
            name: "Bucky Irving",
            position: "RB",
            isSelected: false,
            redraftValue: 5591,
            trend30Day: 630,
            sleeperId: "11584",
          },
          {
            overallRank: 41,
            name: "Tyler Warren",
            position: "TE",
            isSelected: false,
            redraftValue: 3396,
            trend30Day: 160,
            sleeperId: "12518",
          },
          {
            overallRank: 14,
            name: "Derrick Henry",
            position: "RB",
            isSelected: false,
            redraftValue: 6731,
            trend30Day: 813,
            sleeperId: "3198",
          },
          {
            overallRank: 68,
            name: "Matthew Stafford",
            position: "QB",
            isSelected: false,
            redraftValue: 1805,
            trend30Day: 67,
            sleeperId: "421",
          },
          {
            overallRank: 37,
            name: "George Kittle",
            position: "TE",
            isSelected: false,
            redraftValue: 3612,
            trend30Day: 61,
            sleeperId: "4217",
          },
          {
            overallRank: 17,
            name: "Saquon Barkley",
            position: "RB",
            isSelected: false,
            redraftValue: 6202,
            trend30Day: 364,
            sleeperId: "4866",
          },
          {
            overallRank: 19,
            name: "Josh Allen",
            position: "QB",
            isSelected: false,
            redraftValue: 5756,
            trend30Day: 137,
            sleeperId: "4984",
          },
          {
            overallRank: 28,
            name: "A.J. Brown",
            position: "WR",
            isSelected: false,
            redraftValue: 4423,
            trend30Day: 292,
            sleeperId: "5859",
          },
          {
            overallRank: 11,
            name: "CeeDee Lamb",
            position: "WR",
            isSelected: false,
            redraftValue: 7244,
            trend30Day: 321,
            sleeperId: "6786",
          },
          {
            overallRank: 42,
            name: "Tee Higgins",
            position: "WR",
            isSelected: false,
            redraftValue: 3288,
            trend30Day: 503,
            sleeperId: "6801",
          },
          {
            overallRank: 74,
            name: "Jordan Love",
            position: "QB",
            isSelected: false,
            redraftValue: 1654,
            trend30Day: 648,
            sleeperId: "6804",
          },
          {
            overallRank: 25,
            name: "Javonte Williams",
            position: "RB",
            isSelected: false,
            redraftValue: 5052,
            trend30Day: 596,
            sleeperId: "7588",
          },
          {
            overallRank: 8,
            name: "Puka Nacua",
            position: "WR",
            isSelected: false,
            redraftValue: 8771,
            trend30Day: -116,
            sleeperId: "9493",
          },
        ],
        reserve: null,
        roster_id: 4,
        settings: {
          fpts: 2258,
          fpts_against: 2256,
          fpts_against_decimal: 20,
          fpts_decimal: 42,
          losses: 7,
          ppts: 2447,
          ppts_decimal: 2,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 4,
          wins: 8,
        },
        starters: [
          "4984",
          "4866",
          "3198",
          "9493",
          "6786",
          "4217",
          "7588",
          "5859",
          "421",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember2",
          is_bot: false,
          is_owner: null,
          league_id: "1",
          metadata: {
            allow_pn: "on",
            mention_pn: "on",
          },
          settings: null,
          user_id: "2",
        },
        trend30Day: 4476,
        totalValue: 63525,
      },
      {
        co_owners: null,
        keepers: null,
        league_id: "1",
        metadata: {
          record: "WLLWWWWLWLLLLLL",
          streak: "6L",
        },
        owner_id: "3",
        player_map: null,
        players: [
          {
            overallRank: 86,
            name: "Michael Wilson",
            position: "WR",
            isSelected: false,
            redraftValue: 1283,
            trend30Day: 407,
            sleeperId: "10232",
          },
          {
            overallRank: 45,
            name: "Drake Maye",
            position: "QB",
            isSelected: false,
            redraftValue: 3167,
            trend30Day: 58,
            sleeperId: "11564",
          },
          {
            overallRank: 34,
            name: "Emeka Egbuka",
            position: "WR",
            isSelected: false,
            redraftValue: 3785,
            trend30Day: -199,
            sleeperId: "12514",
          },
          {
            overallRank: 22,
            name: "Davante Adams",
            position: "WR",
            isSelected: false,
            redraftValue: 5586,
            trend30Day: 767,
            sleeperId: "2133",
          },
          {
            overallRank: 48,
            name: "Lamar Jackson",
            position: "QB",
            isSelected: false,
            redraftValue: 3101,
            trend30Day: -185,
            sleeperId: "4881",
          },
          {
            overallRank: 16,
            name: "Josh Jacobs",
            position: "RB",
            isSelected: false,
            redraftValue: 6498,
            trend30Day: 395,
            sleeperId: "5850",
          },
          {
            overallRank: 26,
            name: "Justin Jefferson",
            position: "WR",
            isSelected: false,
            redraftValue: 4925,
            trend30Day: 144,
            sleeperId: "6794",
          },
          {
            overallRank: 32,
            name: "Jalen Hurts",
            position: "QB",
            isSelected: false,
            redraftValue: 4058,
            trend30Day: 766,
            sleeperId: "6904",
          },
          {
            overallRank: 36,
            name: "Jaylen Waddle",
            position: "WR",
            isSelected: false,
            redraftValue: 3777,
            trend30Day: 423,
            sleeperId: "7526",
          },
          {
            overallRank: 35,
            name: "Travis Etienne",
            position: "RB",
            isSelected: false,
            redraftValue: 3719,
            trend30Day: 448,
            sleeperId: "7543",
          },
          {
            overallRank: 107,
            name: "Kyle Pitts",
            position: "TE",
            isSelected: false,
            redraftValue: 770,
            trend30Day: 259,
            sleeperId: "7553",
          },
          {
            overallRank: 13,
            name: "James Cook",
            position: "RB",
            isSelected: false,
            redraftValue: 6927,
            trend30Day: 344,
            sleeperId: "8138",
          },
          {
            overallRank: 27,
            name: "Kyren Williams",
            position: "RB",
            isSelected: false,
            redraftValue: 4596,
            trend30Day: -500,
            sleeperId: "8150",
          },
          {
            overallRank: 1,
            name: "Jaxon Smith-Njigba",
            position: "WR",
            isSelected: false,
            redraftValue: 10480,
            trend30Day: 630,
            sleeperId: "9488",
          },
        ],
        reserve: null,
        roster_id: 2,
        settings: {
          fpts: 2133,
          fpts_against: 2402,
          fpts_against_decimal: 38,
          fpts_decimal: 64,
          losses: 9,
          ppts: 2534,
          ppts_decimal: 4,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 2,
          wins: 6,
        },
        starters: [
          "11564",
          "8138",
          "5850",
          "9488",
          "12514",
          "7553",
          "10232",
          "7543",
          "6904",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember3",
          is_bot: false,
          is_owner: null,
          league_id: "1",
          metadata: {
            allow_pn: "on",
            mention_pn: "on",
          },
          settings: null,
          user_id: "3",
        },
        trend30Day: 3757,
        totalValue: 62672,
      },
      {
        co_owners: null,
        keepers: null,
        league_id: "1",
        metadata: {
          record: "LLWLLLWWLWLWLLW",
          streak: "1W",
        },
        owner_id: "4",
        player_map: null,
        players: [
          {
            overallRank: 31,
            name: "Omarion Hampton",
            position: "RB",
            isSelected: false,
            redraftValue: 4050,
            trend30Day: 465,
            sleeperId: "12507",
          },
          {
            overallRank: 38,
            name: "Tetairoa McMillan",
            position: "WR",
            isSelected: false,
            redraftValue: 3598,
            trend30Day: 325,
            sleeperId: "12526",
          },
          {
            overallRank: 80,
            name: "Jared Goff",
            position: "QB",
            isSelected: false,
            redraftValue: 1370,
            trend30Day: 199,
            sleeperId: "3163",
          },
          {
            overallRank: 64,
            name: "Baker Mayfield",
            position: "QB",
            isSelected: false,
            redraftValue: 1921,
            trend30Day: 220,
            sleeperId: "4892",
          },
          {
            overallRank: 65,
            name: "Justin Herbert",
            position: "QB",
            isSelected: false,
            redraftValue: 1884,
            trend30Day: 188,
            sleeperId: "6797",
          },
          {
            overallRank: 4,
            name: "Jonathan Taylor",
            position: "RB",
            isSelected: false,
            redraftValue: 9270,
            trend30Day: -763,
            sleeperId: "6813",
          },
          {
            overallRank: 10,
            name: "Amon-Ra St. Brown",
            position: "WR",
            isSelected: false,
            redraftValue: 7494,
            trend30Day: -483,
            sleeperId: "7547",
          },
          {
            overallRank: 12,
            name: "Trey McBride",
            position: "TE",
            isSelected: false,
            redraftValue: 7035,
            trend30Day: 449,
            sleeperId: "8130",
          },
          {
            overallRank: 15,
            name: "George Pickens",
            position: "WR",
            isSelected: false,
            redraftValue: 6648,
            trend30Day: 94,
            sleeperId: "8137",
          },
          {
            overallRank: 29,
            name: "Chris Olave",
            position: "WR",
            isSelected: false,
            redraftValue: 4174,
            trend30Day: 628,
            sleeperId: "8144",
          },
          {
            overallRank: 46,
            name: "Jameson Williams",
            position: "WR",
            isSelected: false,
            redraftValue: 3121,
            trend30Day: 1489,
            sleeperId: "8148",
          },
          {
            overallRank: 85,
            name: "Brock Purdy",
            position: "QB",
            isSelected: false,
            redraftValue: 1298,
            trend30Day: 188,
            sleeperId: "8183",
          },
          {
            overallRank: 2,
            name: "Jahmyr Gibbs",
            position: "RB",
            isSelected: false,
            redraftValue: 9540,
            trend30Day: -50,
            sleeperId: "9221",
          },
        ],
        reserve: null,
        roster_id: 3,
        settings: {
          fpts: 2317,
          fpts_against: 2365,
          fpts_against_decimal: 38,
          fpts_decimal: 10,
          losses: 9,
          ppts: 2591,
          ppts_decimal: 80,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 3,
          wins: 6,
        },
        starters: [
          "8183",
          "9221",
          "6813",
          "8137",
          "7547",
          "8130",
          "12507",
          "8144",
          "4892",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember4",
          is_bot: false,
          is_owner: null,
          league_id: "1",
          metadata: {
            allow_pn: "on",
            mention_pn: "on",
          },
          settings: null,
          user_id: "4",
        },
        trend30Day: 2949,
        totalValue: 61403,
      },
    ],
    maxTeamValue: 79399,
    leagueID: "1",
    name: "LeagueSample1",
  },
  {
    rosters: [
      {
        co_owners: null,
        keepers: null,
        league_id: "2",
        metadata: {
          record: "WLWLLWWWWWLWWL",
          streak: "1L",
        },
        owner_id: "5",
        player_map: null,
        players: [
          {
            overallRank: 9,
            name: "Rashee Rice",
            position: "WR",
            isSelected: false,
            redraftValue: 7581,
            trend30Day: 1627,
            sleeperId: "10229",
          },
          {
            overallRank: 98,
            name: "Dalton Kincaid",
            position: "TE",
            isSelected: false,
            redraftValue: 942,
            trend30Day: 278,
            sleeperId: "10236",
          },
          {
            overallRank: 54,
            name: "Marvin Harrison Jr",
            position: "WR",
            isSelected: false,
            redraftValue: 2443,
            trend30Day: 110,
            sleeperId: "11628",
          },
          {
            overallRank: 39,
            name: "Ladd McConkey",
            position: "WR",
            isSelected: false,
            redraftValue: 3483,
            trend30Day: 143,
            sleeperId: "11635",
          },
          {
            overallRank: 69,
            name: "Woody Marks",
            position: "RB",
            isSelected: false,
            redraftValue: 1734,
            trend30Day: 373,
            sleeperId: "12474",
          },
          {
            overallRank: 110,
            name: "Harold Fannin",
            position: "TE",
            isSelected: false,
            redraftValue: 627,
            trend30Day: 219,
            sleeperId: "12506",
          },
          {
            overallRank: 139,
            name: "Luther Burden",
            position: "WR",
            isSelected: false,
            redraftValue: 292,
            trend30Day: 163,
            sleeperId: "12519",
          },
          {
            overallRank: 38,
            name: "Tetairoa McMillan",
            position: "WR",
            isSelected: false,
            redraftValue: 3598,
            trend30Day: 325,
            sleeperId: "12526",
          },
          {
            overallRank: 65,
            name: "Justin Herbert",
            position: "QB",
            isSelected: false,
            redraftValue: 1884,
            trend30Day: 188,
            sleeperId: "6797",
          },
          {
            overallRank: 44,
            name: "Rico Dowdle",
            position: "RB",
            isSelected: false,
            redraftValue: 3088,
            trend30Day: -317,
            sleeperId: "7021",
          },
          {
            overallRank: 24,
            name: "Drake London",
            position: "WR",
            isSelected: false,
            redraftValue: 5345,
            trend30Day: 660,
            sleeperId: "8112",
          },
          {
            overallRank: 2,
            name: "Jahmyr Gibbs",
            position: "RB",
            isSelected: false,
            redraftValue: 9540,
            trend30Day: -50,
            sleeperId: "9221",
          },
          {
            overallRank: 156,
            name: "Bryce Young",
            position: "QB",
            isSelected: false,
            redraftValue: 115,
            trend30Day: -25,
            sleeperId: "9228",
          },
        ],
        reserve: ["11589"],
        roster_id: 4,
        settings: {
          fpts: 2000,
          fpts_against: 1826,
          fpts_against_decimal: 14,
          fpts_decimal: 86,
          losses: 5,
          ppts: 2110,
          ppts_decimal: 36,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 7,
          wins: 9,
        },
        starters: [
          "6797",
          "12474",
          "9221",
          "10229",
          "11635",
          "12506",
          "12526",
          "7021",
          "4227",
          "HOU",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember1",
          is_bot: false,
          is_owner: null,
          league_id: "2",
          metadata: {
            allow_pn: "on",
            mention_pn: "on",
          },
          settings: null,
          user_id: "5",
        },
        trend30Day: 3694,
        totalValue: 40672,
      },
      {
        co_owners: null,
        keepers: null,
        league_id: "2",
        metadata: {
          record: "WWWLWWLLWLWWWW",
          streak: "4W",
        },
        owner_id: "6",
        player_map: null,
        players: [
          {
            overallRank: 147,
            name: "Adonai Mitchell",
            position: "WR",
            isSelected: false,
            redraftValue: 217,
            trend30Day: 197,
            sleeperId: "11625",
          },
          {
            overallRank: 31,
            name: "Omarion Hampton",
            position: "RB",
            isSelected: false,
            redraftValue: 4050,
            trend30Day: 465,
            sleeperId: "12507",
          },
          {
            overallRank: 71,
            name: "Jaxson Dart",
            position: "QB",
            isSelected: false,
            redraftValue: 1684,
            trend30Day: 44,
            sleeperId: "12508",
          },
          {
            overallRank: 41,
            name: "Tyler Warren",
            position: "TE",
            isSelected: false,
            redraftValue: 3396,
            trend30Day: 160,
            sleeperId: "12518",
          },
          {
            overallRank: 128,
            name: "Jacory Croskey-Merritt",
            position: "RB",
            isSelected: false,
            redraftValue: 405,
            trend30Day: 99,
            sleeperId: "12533",
          },
          {
            overallRank: 60,
            name: "David Montgomery",
            position: "RB",
            isSelected: false,
            redraftValue: 2044,
            trend30Day: 225,
            sleeperId: "5892",
          },
          {
            overallRank: 11,
            name: "CeeDee Lamb",
            position: "WR",
            isSelected: false,
            redraftValue: 7244,
            trend30Day: 321,
            sleeperId: "6786",
          },
          {
            overallRank: 42,
            name: "Tee Higgins",
            position: "WR",
            isSelected: false,
            redraftValue: 3288,
            trend30Day: 503,
            sleeperId: "6801",
          },
          {
            overallRank: 160,
            name: "Michael Carter",
            position: "RB",
            isSelected: false,
            redraftValue: 84,
            trend30Day: 84,
            sleeperId: "7607",
          },
          {
            overallRank: 46,
            name: "Jameson Williams",
            position: "WR",
            isSelected: false,
            redraftValue: 3121,
            trend30Day: 1489,
            sleeperId: "8148",
          },
          {
            overallRank: 1,
            name: "Jaxon Smith-Njigba",
            position: "WR",
            isSelected: false,
            redraftValue: 10480,
            trend30Day: 630,
            sleeperId: "9488",
          },
        ],
        reserve: null,
        roster_id: 8,
        settings: {
          fpts: 1735,
          fpts_against: 1661,
          fpts_against_decimal: 70,
          fpts_decimal: 46,
          losses: 4,
          ppts: 1953,
          ppts_decimal: 90,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 12,
          wins: 10,
        },
        starters: [
          "12508",
          "12507",
          "7607",
          "9488",
          "6786",
          "12518",
          "8148",
          "6801",
          "5189",
          "NE",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember2",
          is_bot: false,
          is_owner: null,
          league_id: "2",
          metadata: {
            allow_pn: "on",
            mention_pn: "on",
          },
          settings: null,
          user_id: "6",
        },
        trend30Day: 4217,
        totalValue: 36013,
      },
      {
        co_owners: null,
        keepers: null,
        league_id: "2",
        metadata: {
          record: "LLWWLWLWLWWWLW",
          streak: "1W",
        },
        owner_id: "7",
        player_map: null,
        players: [
          {
            overallRank: 82,
            name: "Caleb Williams",
            position: "QB",
            isSelected: false,
            redraftValue: 1363,
            trend30Day: 476,
            sleeperId: "11560",
          },
          {
            overallRank: 47,
            name: "RJ Harvey",
            position: "RB",
            isSelected: false,
            redraftValue: 3047,
            trend30Day: 728,
            sleeperId: "12489",
          },
          {
            overallRank: 14,
            name: "Derrick Henry",
            position: "RB",
            isSelected: false,
            redraftValue: 6731,
            trend30Day: 813,
            sleeperId: "3198",
          },
          {
            overallRank: 49,
            name: "Dak Prescott",
            position: "QB",
            isSelected: false,
            redraftValue: 2951,
            trend30Day: 943,
            sleeperId: "3294",
          },
          {
            overallRank: 37,
            name: "George Kittle",
            position: "TE",
            isSelected: false,
            redraftValue: 3612,
            trend30Day: 61,
            sleeperId: "4217",
          },
          {
            overallRank: 94,
            name: "Dallas Goedert",
            position: "TE",
            isSelected: false,
            redraftValue: 1111,
            trend30Day: 48,
            sleeperId: "5022",
          },
          {
            overallRank: 28,
            name: "A.J. Brown",
            position: "WR",
            isSelected: false,
            redraftValue: 4423,
            trend30Day: 292,
            sleeperId: "5859",
          },
          {
            overallRank: 73,
            name: "Jakobi Meyers",
            position: "WR",
            isSelected: false,
            redraftValue: 1642,
            trend30Day: 809,
            sleeperId: "5947",
          },
          {
            overallRank: 84,
            name: "Khalil Shakir",
            position: "WR",
            isSelected: false,
            redraftValue: 1327,
            trend30Day: 459,
            sleeperId: "8134",
          },
          {
            overallRank: 15,
            name: "George Pickens",
            position: "WR",
            isSelected: false,
            redraftValue: 6648,
            trend30Day: 94,
            sleeperId: "8137",
          },
          {
            overallRank: 56,
            name: "Kenneth Walker",
            position: "RB",
            isSelected: false,
            redraftValue: 2328,
            trend30Day: 46,
            sleeperId: "8151",
          },
          {
            overallRank: 131,
            name: "Tyjae Spears",
            position: "RB",
            isSelected: false,
            redraftValue: 387,
            trend30Day: -152,
            sleeperId: "9508",
          },
        ],
        reserve: null,
        roster_id: 1,
        settings: {
          fpts: 1747,
          fpts_against: 1796,
          fpts_against_decimal: 62,
          fpts_decimal: 28,
          losses: 6,
          ppts: 1933,
          ppts_decimal: 98,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 2,
          wins: 8,
        },
        starters: [
          "3294",
          "12489",
          "3198",
          "5947",
          "5859",
          "4217",
          "8134",
          "8137",
          "12711",
          "JAX",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember3",
          is_bot: false,
          is_owner: true,
          league_id: "2",
          metadata: {
            allow_pn: "on",
            allow_sms: "on",
            mention_pn: "on",
          },
          settings: null,
          user_id: "7",
        },
        trend30Day: 4617,
        totalValue: 35570,
      },
      {
        co_owners: null,
        keepers: null,
        league_id: "2",
        metadata: {
          record: "WWLLWLWWWWWWWW",
          streak: "8W",
        },
        owner_id: "8",
        player_map: null,
        players: [
          {
            overallRank: 137,
            name: "Tre Tucker",
            position: "WR",
            isSelected: false,
            redraftValue: 352,
            trend30Day: -73,
            sleeperId: "10213",
          },
          {
            overallRank: 164,
            name: "Andrei Iosivas",
            position: "WR",
            isSelected: false,
            redraftValue: 71,
            trend30Day: -68,
            sleeperId: "10226",
          },
          {
            overallRank: 111,
            name: "Emanuel Wilson",
            position: "RB",
            isSelected: false,
            redraftValue: 618,
            trend30Day: 9,
            sleeperId: "11435",
          },
          {
            overallRank: 105,
            name: "Kimani Vidal",
            position: "RB",
            isSelected: false,
            redraftValue: 804,
            trend30Day: 320,
            sleeperId: "11647",
          },
          {
            overallRank: 141,
            name: "Darren Waller",
            position: "TE",
            isSelected: false,
            redraftValue: 273,
            trend30Day: 240,
            sleeperId: "2505",
          },
          {
            overallRank: 19,
            name: "Josh Allen",
            position: "QB",
            isSelected: false,
            redraftValue: 5756,
            trend30Day: 137,
            sleeperId: "4984",
          },
          {
            overallRank: 57,
            name: "D'Andre Swift",
            position: "RB",
            isSelected: false,
            redraftValue: 2293,
            trend30Day: 458,
            sleeperId: "6790",
          },
          {
            overallRank: 36,
            name: "Jaylen Waddle",
            position: "WR",
            isSelected: false,
            redraftValue: 3777,
            trend30Day: 423,
            sleeperId: "7526",
          },
          {
            overallRank: 6,
            name: "Ja'Marr Chase",
            position: "WR",
            isSelected: false,
            redraftValue: 9111,
            trend30Day: -177,
            sleeperId: "7564",
          },
          {
            overallRank: 126,
            name: "Tyler Allgeier",
            position: "RB",
            isSelected: false,
            redraftValue: 443,
            trend30Day: -74,
            sleeperId: "8132",
          },
          {
            overallRank: 13,
            name: "James Cook",
            position: "RB",
            isSelected: false,
            redraftValue: 6927,
            trend30Day: 344,
            sleeperId: "8138",
          },
          {
            overallRank: 43,
            name: "Jaylen Warren",
            position: "RB",
            isSelected: false,
            redraftValue: 3117,
            trend30Day: 937,
            sleeperId: "8228",
          },
          {
            overallRank: 101,
            name: "Quentin Johnston",
            position: "WR",
            isSelected: false,
            redraftValue: 865,
            trend30Day: 72,
            sleeperId: "9754",
          },
        ],
        reserve: ["10859"],
        roster_id: 9,
        settings: {
          fpts: 1887,
          fpts_against: 1689,
          fpts_against_decimal: 54,
          fpts_decimal: 50,
          losses: 3,
          ppts: 2051,
          ppts_decimal: 20,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 9,
          wins: 11,
        },
        starters: [
          "4984",
          "8138",
          "6790",
          "7564",
          "9754",
          "2505",
          "8228",
          "7526",
          "11533",
          "TB",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember4",
          is_bot: false,
          is_owner: null,
          league_id: "2",
          metadata: {
            allow_pn: "on",
            allow_sms: "on",
            archived: "off",
            mention_pn: "on",
          },
          settings: null,
          user_id: "8",
        },
        trend30Day: 2548,
        totalValue: 34407,
      },
      {
        co_owners: null,
        keepers: null,
        league_id: "2",
        metadata: {
          record: "WWLLLWLWWLWLLL",
          streak: "3L",
        },
        owner_id: "9",
        player_map: null,
        players: [
          {
            overallRank: 169,
            name: "AJ Barner",
            position: "TE",
            isSelected: false,
            redraftValue: 53,
            trend30Day: -48,
            sleeperId: "11603",
          },
          {
            overallRank: 103,
            name: "Xavier Worthy",
            position: "WR",
            isSelected: false,
            redraftValue: 847,
            trend30Day: 224,
            sleeperId: "11624",
          },
          {
            overallRank: 75,
            name: "Kyle Monangai",
            position: "RB",
            isSelected: false,
            redraftValue: 1484,
            trend30Day: 799,
            sleeperId: "12534",
          },
          {
            overallRank: 88,
            name: "Kareem Hunt",
            position: "RB",
            isSelected: false,
            redraftValue: 1240,
            trend30Day: 145,
            sleeperId: "4098",
          },
          {
            overallRank: 32,
            name: "Jalen Hurts",
            position: "QB",
            isSelected: false,
            redraftValue: 4058,
            trend30Day: 766,
            sleeperId: "6904",
          },
          {
            overallRank: 104,
            name: "Juwan Johnson",
            position: "TE",
            isSelected: false,
            redraftValue: 838,
            trend30Day: 51,
            sleeperId: "7002",
          },
          {
            overallRank: 35,
            name: "Travis Etienne",
            position: "RB",
            isSelected: false,
            redraftValue: 3719,
            trend30Day: 448,
            sleeperId: "7543",
          },
          {
            overallRank: 21,
            name: "Nico Collins",
            position: "WR",
            isSelected: false,
            redraftValue: 5629,
            trend30Day: 708,
            sleeperId: "7569",
          },
          {
            overallRank: 122,
            name: "Bam Knight",
            position: "RB",
            isSelected: false,
            redraftValue: 462,
            trend30Day: 227,
            sleeperId: "8122",
          },
          {
            overallRank: 29,
            name: "Chris Olave",
            position: "WR",
            isSelected: false,
            redraftValue: 4174,
            trend30Day: 628,
            sleeperId: "8144",
          },
          {
            overallRank: 7,
            name: "De'Von Achane",
            position: "RB",
            isSelected: false,
            redraftValue: 8960,
            trend30Day: 368,
            sleeperId: "9226",
          },
          {
            overallRank: 50,
            name: "Zay Flowers",
            position: "WR",
            isSelected: false,
            redraftValue: 2786,
            trend30Day: 455,
            sleeperId: "9997",
          },
        ],
        reserve: null,
        roster_id: 7,
        settings: {
          fpts: 1788,
          fpts_against: 1831,
          fpts_against_decimal: 38,
          fpts_decimal: 52,
          losses: 8,
          ppts: 1969,
          ppts_decimal: 54,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 4,
          wins: 6,
        },
        starters: [
          "6904",
          "9226",
          "7543",
          "7569",
          "8144",
          "7002",
          "4098",
          "9997",
          "1945",
          "DEN",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember5",
          is_bot: false,
          is_owner: null,
          league_id: "2",
          metadata: {
            allow_pn: "on",
            mention_pn: "on",
          },
          settings: null,
          user_id: "9",
        },
        trend30Day: 4771,
        totalValue: 34250,
      },
      {
        co_owners: null,
        keepers: null,
        league_id: "2",
        metadata: {
          record: "WWWWLWLWLWWLWW",
          streak: "2W",
        },
        owner_id: "10",
        player_map: null,
        players: [
          {
            overallRank: 113,
            name: "Chris Rodriguez",
            position: "RB",
            isSelected: false,
            redraftValue: 610,
            trend30Day: 214,
            sleeperId: "10219",
          },
          {
            overallRank: 127,
            name: "Jayden Reed",
            position: "WR",
            isSelected: false,
            redraftValue: 436,
            trend30Day: 275,
            sleeperId: "10222",
          },
          {
            overallRank: 45,
            name: "Drake Maye",
            position: "QB",
            isSelected: false,
            redraftValue: 3167,
            trend30Day: 58,
            sleeperId: "11564",
          },
          {
            overallRank: 116,
            name: "Blake Corum",
            position: "RB",
            isSelected: false,
            redraftValue: 531,
            trend30Day: 325,
            sleeperId: "11586",
          },
          {
            overallRank: 66,
            name: "Rome Odunze",
            position: "WR",
            isSelected: false,
            redraftValue: 1844,
            trend30Day: -254,
            sleeperId: "11620",
          },
          {
            overallRank: 91,
            name: "Ricky Pearsall",
            position: "WR",
            isSelected: false,
            redraftValue: 1134,
            trend30Day: 135,
            sleeperId: "11638",
          },
          {
            overallRank: 176,
            name: "Dylan Sampson",
            position: "RB",
            isSelected: false,
            redraftValue: 27,
            trend30Day: 27,
            sleeperId: "12469",
          },
          {
            overallRank: 33,
            name: "TreVeyon Henderson",
            position: "RB",
            isSelected: false,
            redraftValue: 3801,
            trend30Day: -368,
            sleeperId: "12529",
          },
          {
            overallRank: 117,
            name: "Jacoby Brissett",
            position: "QB",
            isSelected: false,
            redraftValue: 544,
            trend30Day: 85,
            sleeperId: "3257",
          },
          {
            overallRank: 12,
            name: "Trey McBride",
            position: "TE",
            isSelected: false,
            redraftValue: 7035,
            trend30Day: 449,
            sleeperId: "8130",
          },
          {
            overallRank: 23,
            name: "Chase Brown",
            position: "RB",
            isSelected: false,
            redraftValue: 5312,
            trend30Day: 1163,
            sleeperId: "9224",
          },
          {
            overallRank: 5,
            name: "Bijan Robinson",
            position: "RB",
            isSelected: false,
            redraftValue: 9138,
            trend30Day: 562,
            sleeperId: "9509",
          },
        ],
        reserve: null,
        roster_id: 10,
        settings: {
          fpts: 1893,
          fpts_against: 1791,
          fpts_against_decimal: 12,
          fpts_decimal: 62,
          losses: 4,
          ppts: 2002,
          ppts_decimal: 92,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 11,
          wins: 10,
        },
        starters: [
          "11564",
          "9509",
          "10219",
          "10222",
          "11638",
          "8130",
          "9224",
          "12529",
          "3451",
          "SEA",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember6",
          is_bot: false,
          is_owner: null,
          league_id: "2",
          metadata: {
            allow_pn: "on",
            mention_pn: "on",
          },
          settings: null,
          user_id: "10",
        },
        trend30Day: 2671,
        totalValue: 33579,
      },
      {
        co_owners: null,
        keepers: null,
        league_id: "2",
        metadata: {
          record: "LLLLLLLLWLLLLW",
          streak: "1W",
        },
        owner_id: "11",
        player_map: null,
        players: [
          {
            overallRank: 20,
            name: "Bucky Irving",
            position: "RB",
            isSelected: false,
            redraftValue: 5591,
            trend30Day: 630,
            sleeperId: "11584",
          },
          {
            overallRank: 83,
            name: "Tyrone Tracy",
            position: "RB",
            isSelected: false,
            redraftValue: 1323,
            trend30Day: 320,
            sleeperId: "11655",
          },
          {
            overallRank: 115,
            name: "Jayden Higgins",
            position: "WR",
            isSelected: false,
            redraftValue: 565,
            trend30Day: 366,
            sleeperId: "12484",
          },
          {
            overallRank: 22,
            name: "Davante Adams",
            position: "WR",
            isSelected: false,
            redraftValue: 5586,
            trend30Day: 767,
            sleeperId: "2133",
          },
          {
            overallRank: 55,
            name: "Stefon Diggs",
            position: "WR",
            isSelected: false,
            redraftValue: 2415,
            trend30Day: 400,
            sleeperId: "2449",
          },
          {
            overallRank: 62,
            name: "Aaron Jones",
            position: "RB",
            isSelected: false,
            redraftValue: 1927,
            trend30Day: 294,
            sleeperId: "4199",
          },
          {
            overallRank: 68,
            name: "Matthew Stafford",
            position: "QB",
            isSelected: false,
            redraftValue: 1805,
            trend30Day: 67,
            sleeperId: "421",
          },
          {
            overallRank: 17,
            name: "Saquon Barkley",
            position: "RB",
            isSelected: false,
            redraftValue: 6202,
            trend30Day: 364,
            sleeperId: "4866",
          },
          {
            overallRank: 48,
            name: "Lamar Jackson",
            position: "QB",
            isSelected: false,
            redraftValue: 3101,
            trend30Day: -185,
            sleeperId: "4881",
          },
          {
            overallRank: 78,
            name: "DJ Moore",
            position: "WR",
            isSelected: false,
            redraftValue: 1364,
            trend30Day: 472,
            sleeperId: "4983",
          },
          {
            overallRank: 92,
            name: "Mark Andrews",
            position: "TE",
            isSelected: false,
            redraftValue: 1127,
            trend30Day: 198,
            sleeperId: "5012",
          },
          {
            overallRank: 145,
            name: "Cade Otton",
            position: "TE",
            isSelected: false,
            redraftValue: 225,
            trend30Day: -110,
            sleeperId: "8111",
          },
          {
            overallRank: 89,
            name: "Alec Pierce",
            position: "WR",
            isSelected: false,
            redraftValue: 1251,
            trend30Day: 375,
            sleeperId: "8142",
          },
        ],
        reserve: ["12481"],
        roster_id: 6,
        settings: {
          fpts: 1669,
          fpts_against: 1954,
          fpts_against_decimal: 22,
          fpts_decimal: 48,
          losses: 12,
          ppts: 1907,
          ppts_decimal: 50,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 8,
          wins: 2,
        },
        starters: [
          "4881",
          "11584",
          "4866",
          "2133",
          "8142",
          "5012",
          "4983",
          "4199",
          "8259",
          "PIT",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember7",
          is_bot: false,
          is_owner: null,
          league_id: "2",
          metadata: {
            allow_pn: "on",
            mention_pn: "on",
          },
          settings: null,
          user_id: "11",
        },
        trend30Day: 3958,
        totalValue: 32482,
      },
      {
        co_owners: null,
        keepers: null,
        league_id: "2",
        metadata: {
          record: "LWLWWWWLWLLWWL",
          streak: "1L",
        },
        owner_id: "12",
        player_map: null,
        players: [
          {
            overallRank: 152,
            name: "Devaughn Vele",
            position: "WR",
            isSelected: false,
            redraftValue: 160,
            trend30Day: 160,
            sleeperId: "11834",
          },
          {
            overallRank: 79,
            name: "Mike Evans",
            position: "WR",
            isSelected: false,
            redraftValue: 1358,
            trend30Day: 1274,
            sleeperId: "2216",
          },
          {
            overallRank: 3,
            name: "Christian McCaffrey",
            position: "RB",
            isSelected: false,
            redraftValue: 9464,
            trend30Day: -628,
            sleeperId: "4034",
          },
          {
            overallRank: 70,
            name: "Alvin Kamara",
            position: "RB",
            isSelected: false,
            redraftValue: 1664,
            trend30Day: 109,
            sleeperId: "4035",
          },
          {
            overallRank: 64,
            name: "Baker Mayfield",
            position: "QB",
            isSelected: false,
            redraftValue: 1921,
            trend30Day: 220,
            sleeperId: "4892",
          },
          {
            overallRank: 58,
            name: "Terry McLaurin",
            position: "WR",
            isSelected: false,
            redraftValue: 2295,
            trend30Day: 1200,
            sleeperId: "5927",
          },
          {
            overallRank: 74,
            name: "Jordan Love",
            position: "QB",
            isSelected: false,
            redraftValue: 1654,
            trend30Day: 648,
            sleeperId: "6804",
          },
          {
            overallRank: 40,
            name: "DeVonta Smith",
            position: "WR",
            isSelected: false,
            redraftValue: 3434,
            trend30Day: 310,
            sleeperId: "7525",
          },
          {
            overallRank: 25,
            name: "Javonte Williams",
            position: "RB",
            isSelected: false,
            redraftValue: 5052,
            trend30Day: 596,
            sleeperId: "7588",
          },
          {
            overallRank: 72,
            name: "Jake Ferguson",
            position: "TE",
            isSelected: false,
            redraftValue: 1653,
            trend30Day: 146,
            sleeperId: "8110",
          },
          {
            overallRank: 100,
            name: "Romeo Doubs",
            position: "WR",
            isSelected: false,
            redraftValue: 876,
            trend30Day: 232,
            sleeperId: "8121",
          },
          {
            overallRank: 76,
            name: "Wan'Dale Robinson",
            position: "WR",
            isSelected: false,
            redraftValue: 1449,
            trend30Day: 236,
            sleeperId: "8126",
          },
        ],
        reserve: null,
        roster_id: 12,
        settings: {
          fpts: 1762,
          fpts_against: 1688,
          fpts_against_decimal: 42,
          fpts_decimal: 24,
          losses: 6,
          ppts: 1952,
          ppts_decimal: 90,
          ties: 0,
          total_moves: 0,
          waiver_budget_used: 0,
          waiver_position: 6,
          wins: 8,
        },
        starters: [
          "4892",
          "4034",
          "7588",
          "8126",
          "2216",
          "8110",
          "5927",
          "7525",
          "11786",
          "NO",
        ],
        taxi: null,
        user: {
          display_name: "LeagueMember8",
          is_bot: false,
          is_owner: null,
          league_id: "2",
          metadata: {
            allow_pn: "on",
            allow_sms: "on",
            mention_pn: "on",
          },
          settings: null,
          user_id: "12",
        },
        trend30Day: 4503,
        totalValue: 30980,
      },
    ],
    maxTeamValue: 40672,
    leagueID: "2",
    name: "LeagueSample2",
  },
];
